name: CD - Production

on:
  push:
    branches:
      - main

jobs:
  publish-app-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish app to production
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build the app
        run: pnpm -F @pas-fute-fute/app build:cloudflare

      - name: Publish to Cloudflare Pages
        uses: AdrianGonz97/refined-cf-pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: pas-fute-fute
          workingDirectory: packages/app
          directory: dist
          deploymentName: Production App
          branch: main
          wranglerVersion: '3'
