name: CI - App 

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci-app:
    name: CI - App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/app

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

    #   - name: Type check
    #     run: pnpm typecheck

    #   - name: Run unit test
    #     run: pnpm test

      - name: Build the app for cloudflare
        run: pnpm build:cloudflare